"""empty message

Revision ID: 182d27742547
Revises: None
Create Date: 2016-04-27 09:25:42.944307

"""

# revision identifiers, used by Alembic.
revision = '182d27742547'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_task', sa.Column('status', sa.String(length=16), nullable=True))
    op.drop_column('celery_task', 'status_flag')
    op.drop_column('celery_task', 'status_string')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_task', sa.Column('status_string', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('celery_task', sa.Column('status_flag', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('celery_task', 'status')
    ### end Alembic commands ###
