"""empty message

Revision ID: 25ff2a9db4d3
Revises: None
Create Date: 2016-04-12 19:31:38.477548

"""

# revision identifiers, used by Alembic.
revision = '25ff2a9db4d3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_dataset')
    op.drop_column('annotation', 'strand_corrected_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('strand_corrected_sequence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('project_dataset',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], [u'dataset.id'], name=u'project_dataset_dataset_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], [u'project.id'], name=u'project_dataset_project_id_fkey'),
    sa.PrimaryKeyConstraint('project_id', 'dataset_id', name=u'project_dataset_pkey')
    )
    ### end Alembic commands ###
