"""empty message

Revision ID: 26da4847fc69
Revises: None
Create Date: 2016-04-12 19:37:11.397109

"""

# revision identifiers, used by Alembic.
revision = '26da4847fc69'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_dataset')
    op.add_column('analysis', sa.Column('directory', sa.String(length=256), nullable=True))
    op.add_column('analysis', sa.Column('error', sa.String(length=256), nullable=True))
    op.add_column('analysis', sa.Column('files_to_analyze', postgresql.ARRAY(Integer()), nullable=True))
    op.drop_column('annotation', 'strand_corrected_sequence')
    op.add_column('dataset', sa.Column('directory', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'directory')
    op.add_column('annotation', sa.Column('strand_corrected_sequence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('analysis', 'files_to_analyze')
    op.drop_column('analysis', 'error')
    op.drop_column('analysis', 'directory')
    op.create_table('project_dataset',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], [u'dataset.id'], name=u'project_dataset_dataset_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], [u'project.id'], name=u'project_dataset_project_id_fkey'),
    sa.PrimaryKeyConstraint('project_id', 'dataset_id', name=u'project_dataset_pkey')
    )
    ### end Alembic commands ###
