"""empty message

Revision ID: 493215d05f52
Revises: None
Create Date: 2016-04-12 19:39:42.096060

"""

# revision identifiers, used by Alembic.
revision = '493215d05f52'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('directory', sa.String(length=256), nullable=True))
    op.add_column('analysis', sa.Column('error', sa.String(length=256), nullable=True))
    op.add_column('analysis', sa.Column('files_to_analyze', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.add_column('dataset', sa.Column('directory', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'directory')
    op.drop_column('analysis', 'files_to_analyze')
    op.drop_column('analysis', 'error')
    op.drop_column('analysis', 'directory')
    ### end Alembic commands ###
