"""empty message

Revision ID: 52cc87210de
Revises: 581c5a8a69df
Create Date: 2016-04-07 15:10:30.456388

"""

# revision identifiers, used by Alembic.
revision = '52cc87210de'
down_revision = '581c5a8a69df'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_dataset',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'dataset_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_dataset')
    ### end Alembic commands ###
