"""empty message

Revision ID: 549c526753fa
Revises: fe6fad71c7d
Create Date: 2016-04-26 14:27:11.016888

"""

# revision identifiers, used by Alembic.
revision = '549c526753fa'
down_revision = 'fe6fad71c7d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'old_dropbox_path')
    op.drop_column('user', 'old_scratch_path')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('old_scratch_path', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('old_dropbox_path', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    ### end Alembic commands ###
