"""empty message

Revision ID: fd783bcb14f
Revises: None
Create Date: 2016-04-11 14:32:25.994617

"""

# revision identifiers, used by Alembic.
revision = 'fd783bcb14f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_dataset')
    op.add_column('annotation', sa.Column('command', sa.String(), nullable=True))
    op.add_column('annotation', sa.Column('errors', sa.String(), nullable=True))
    op.add_column('annotation', sa.Column('five_prime_annotation', sa.String(), nullable=True))
    op.add_column('annotation', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('annotation', sa.Column('percent_identity', sa.FLOAT(), nullable=True))
    op.add_column('annotation', sa.Column('reading_frames', sa.String(), nullable=True))
    op.add_column('annotation', sa.Column('strand_corrected_sequence', sa.String(), nullable=True))
    op.add_column('annotation', sa.Column('three_prime_annotation', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation', 'three_prime_annotation')
    op.drop_column('annotation', 'strand_corrected_sequence')
    op.drop_column('annotation', 'reading_frames')
    op.drop_column('annotation', 'percent_identity')
    op.drop_column('annotation', 'notes')
    op.drop_column('annotation', 'five_prime_annotation')
    op.drop_column('annotation', 'errors')
    op.drop_column('annotation', 'command')
    op.create_table('project_dataset',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], [u'dataset.id'], name=u'project_dataset_dataset_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], [u'project.id'], name=u'project_dataset_project_id_fkey'),
    sa.PrimaryKeyConstraint('project_id', 'dataset_id', name=u'project_dataset_pkey')
    )
    ### end Alembic commands ###
