"""empty message

Revision ID: 129783c2593b
Revises: 43eae81fc081
Create Date: 2015-11-17 19:14:34.103884

"""

# revision identifiers, used by Alembic.
revision = '129783c2593b'
down_revision = '43eae81fc081'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('analysis', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'file', 'analysis', ['analysis'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_column('file', 'analysis')
    ### end Alembic commands ###
