"""empty message

Revision ID: 146cd67f2d78
Revises: 1b820ae444a6
Create Date: 2016-03-28 05:42:10.077372

"""

# revision identifiers, used by Alembic.
revision = '146cd67f2d78'
down_revision = '1b820ae444a6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('header', sa.String(), nullable=True))
    op.add_column('annotation', sa.Column('read_qualities', sa.String(), nullable=True))
    op.add_column('annotation', sa.Column('read_sequences', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation', 'read_sequences')
    op.drop_column('annotation', 'read_qualities')
    op.drop_column('annotation', 'header')
    ### end Alembic commands ###
