"""empty message

Revision ID: 15c107e9780d
Revises: 38eac52c8a4b
Create Date: 2017-02-19 16:54:06.845204

"""

# revision identifiers, used by Alembic.
revision = '15c107e9780d'
down_revision = '38eac52c8a4b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('distance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allele_id_1', sa.Integer(), nullable=True),
    sa.Column('allele_id_2', sa.Integer(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('value', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'allele', sa.Column('species_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'allele', 'species', ['species_id'], ['id'])
    op.drop_column(u'allele', 'species')
    op.create_foreign_key('log_file_id', 'analysis', 'file', ['log_file_id'], ['id'], use_alter=True)
    op.create_foreign_key('zip_file_id', 'analysis', 'file', ['zip_file_id'], ['id'], use_alter=True)
    op.create_foreign_key('traceback_file_id', 'analysis', 'file', ['traceback_file_id'], ['id'], use_alter=True)
    op.create_foreign_key('traceback_file_id', 'analysis', 'file', ['settings_file_id'], ['id'], use_alter=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('traceback_file_id', 'analysis', type_='foreignkey')
    op.drop_constraint('traceback_file_id', 'analysis', type_='foreignkey')
    op.drop_constraint('zip_file_id', 'analysis', type_='foreignkey')
    op.drop_constraint('log_file_id', 'analysis', type_='foreignkey')
    op.add_column(u'allele', sa.Column('species', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'allele', type_='foreignkey')
    op.drop_column(u'allele', 'species_id')
    op.drop_table('distance')
    ### end Alembic commands ###
