"""empty message

Revision ID: 1751a5032684
Revises: 3a4cbcab5258
Create Date: 2017-02-15 22:36:39.562233

"""

# revision identifiers, used by Alembic.
revision = '1751a5032684'
down_revision = '3a4cbcab5258'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allele', sa.Column('sequence_gene', sa.TEXT(), nullable=True))
    op.add_column('allele', sa.Column('sequence_nuc', sa.TEXT(), nullable=True))
    op.add_column('allele', sa.Column('sequence_prot', sa.TEXT(), nullable=True))
    op.create_foreign_key('log_file_id', 'analysis', 'file', ['log_file_id'], ['id'], use_alter=True)
    op.create_foreign_key('zip_file_id', 'analysis', 'file', ['zip_file_id'], ['id'], use_alter=True)
    op.create_foreign_key('traceback_file_id', 'analysis', 'file', ['traceback_file_id'], ['id'], use_alter=True)
    op.create_foreign_key('traceback_file_id', 'analysis', 'file', ['settings_file_id'], ['id'], use_alter=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('traceback_file_id', 'analysis', type_='foreignkey')
    op.drop_constraint('traceback_file_id', 'analysis', type_='foreignkey')
    op.drop_constraint('zip_file_id', 'analysis', type_='foreignkey')
    op.drop_constraint('log_file_id', 'analysis', type_='foreignkey')
    op.drop_column('allele', 'sequence_prot')
    op.drop_column('allele', 'sequence_nuc')
    op.drop_column('allele', 'sequence_gene')
    ### end Alembic commands ###
