"""empty message

Revision ID: 1b820ae444a6
Revises: cfd9df6264f
Create Date: 2015-11-19 18:05:07.652371

"""

# revision identifiers, used by Alembic.
revision = '1b820ae444a6'
down_revision = 'cfd9df6264f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('file_size', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'file_size')
    ### end Alembic commands ###
