"""empty message

Revision ID: 1df9dea0f71a
Revises: 897e5936903
Create Date: 2015-11-17 15:18:39.528740

"""

# revision identifiers, used by Alembic.
revision = '1df9dea0f71a'
down_revision = '897e5936903'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('active_command', sa.String(length=512), nullable=True))
    op.add_column('analysis', sa.Column('available', sa.Boolean(), nullable=True))
    op.add_column('analysis', sa.Column('inserted_into_db', sa.Boolean(), nullable=True))
    op.add_column('analysis', sa.Column('status', sa.String(length=256), nullable=True))
    op.drop_column('analysis', 'passed_filter')
    op.drop_column('analysis', 'command')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('command', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('analysis', sa.Column('passed_filter', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('analysis', 'status')
    op.drop_column('analysis', 'inserted_into_db')
    op.drop_column('analysis', 'available')
    op.drop_column('analysis', 'active_command')
    ### end Alembic commands ###
