"""empty message

Revision ID: 1edbeaed2071
Revises: None
Create Date: 2016-12-01 16:19:45.773322

"""

# revision identifiers, used by Alembic.
revision = '1edbeaed2071'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('log_file_id', 'analysis', 'file', ['log_file_id'], ['id'], use_alter=True)
    op.create_foreign_key('zip_file_id', 'analysis', 'file', ['zip_file_id'], ['id'], use_alter=True)
    op.create_foreign_key('traceback_file_id', 'analysis', 'file', ['traceback_file_id'], ['id'], use_alter=True)
    op.create_foreign_key('traceback_file_id', 'analysis', 'file', ['settings_file_id'], ['id'], use_alter=True)
    op.add_column('user', sa.Column('authorized', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authorized')
    op.drop_constraint('traceback_file_id', 'analysis', type_='foreignkey')
    op.drop_constraint('traceback_file_id', 'analysis', type_='foreignkey')
    op.drop_constraint('zip_file_id', 'analysis', type_='foreignkey')
    op.drop_constraint('log_file_id', 'analysis', type_='foreignkey')
    ### end Alembic commands ###
