"""empty message

Revision ID: 2124bb2bb1a7
Revises: 4d86bb1e6c5
Create Date: 2016-05-27 07:44:30.145388

"""

# revision identifiers, used by Alembic.
revision = '2124bb2bb1a7'
down_revision = '4d86bb1e6c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('line_count', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'line_count')
    ### end Alembic commands ###
