"""empty message

Revision ID: 2186c8328cc1
Revises: None
Create Date: 2016-04-13 13:14:24.242225

"""

# revision identifiers, used by Alembic.
revision = '2186c8328cc1'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('analysis', 'directory')
    #op.drop_column('analysis', 'files_to_analyze')
    #op.drop_column('analysis', 'error')
    #op.drop_column('annotation', 'strand_corrected_sequence')
    op.add_column('dataset', sa.Column('adjuvant', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('cell_markers_used', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('cell_number', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('cell_selection_kit_name', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('contains_rna_seq_data', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('experiment_name', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('gsaf_barcode', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('isotypes_sequenced', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('json_id', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('lab_notebook_source', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('list_of_polymerases_used', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('mid_tag', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('owners_of_experiment', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('pairing_technique', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('person_who_prepared_library', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('primer_set_name', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('read_access', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('reverse_primer_used_in_rt_step', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('sample_preparation_date', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('sequencing_platform', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('sequencing_submission_number', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('target_reads', sa.String(length=256), nullable=True))
    op.add_column('dataset', sa.Column('template_type', sa.String(length=256), nullable=True))
    #op.drop_column('dataset', 'directory')
    ### end Alembic commands ###


def downgrade():
    
    op.drop_column('dataset', 'template_type')
    op.drop_column('dataset', 'target_reads')
    op.drop_column('dataset', 'sequencing_submission_number')
    op.drop_column('dataset', 'sequencing_platform')
    op.drop_column('dataset', 'sample_preparation_date')
    op.drop_column('dataset', 'reverse_primer_used_in_rt_step')
    op.drop_column('dataset', 'read_access')
    op.drop_column('dataset', 'primer_set_name')
    op.drop_column('dataset', 'person_who_prepared_library')
    op.drop_column('dataset', 'pairing_technique')
    op.drop_column('dataset', 'owners_of_experiment')
    op.drop_column('dataset', 'mid_tag')
    op.drop_column('dataset', 'list_of_polymerases_used')
    op.drop_column('dataset', 'lab_notebook_source')
    op.drop_column('dataset', 'json_id')
    op.drop_column('dataset', 'isotypes_sequenced')
    op.drop_column('dataset', 'gsaf_barcode')
    op.drop_column('dataset', 'experiment_name')
    op.drop_column('dataset', 'contains_rna_seq_data')
    op.drop_column('dataset', 'cell_selection_kit_name')
    op.drop_column('dataset', 'cell_number')
    op.drop_column('dataset', 'cell_markers_used')
    op.drop_column('dataset', 'adjuvant')
    op.add_column('annotation', sa.Column('strand_corrected_sequence', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('analysis', sa.Column('error', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    #op.add_column('analysis', sa.Column('files_to_analyze', postgresql.ARRAY(INTEGER()), autoincrement=False, nullable=True))
    op.add_column('analysis', sa.Column('directory', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    ### end Alembic commands ###
