"""empty message

Revision ID: 238ab78e21e3
Revises: None
Create Date: 2016-04-19 11:07:40.147364

"""

# revision identifiers, used by Alembic.
revision = '238ab78e21e3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('old_dropbox_path', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('old_scratch_path', sa.String(length=256), nullable=True))
    op.add_column('user', sa.Column('root_path', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'root_path')
    op.drop_column('user', 'old_scratch_path')
    op.drop_column('user', 'old_dropbox_path')
    ### end Alembic commands ###
