"""empty message

Revision ID: 26a39132f209
Revises: 8fa97a2b0fd
Create Date: 2015-11-19 13:28:17.042297

"""

# revision identifiers, used by Alembic.
revision = '26a39132f209'
down_revision = '8fa97a2b0fd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('primary_data_file_ids', postgresql.ARRAY(sa.Integer()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'primary_data_file_ids')
    ### end Alembic commands ###
