"""empty message

Revision ID: 273c9e8eb1cc
Revises: 45d9ecbd0b56
Create Date: 2016-03-31 13:52:31.246365

"""

# revision identifiers, used by Alembic.
revision = '273c9e8eb1cc'
down_revision = '45d9ecbd0b56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_projects',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('project', sa.Integer(), nullable=True),
    sa.Column('read_only', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    op.drop_table('user_experiments')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_experiments',
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experiment', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('read_only', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['experiment'], [u'experiment.id'], name=u'user_experiments_experiment_fkey'),
    sa.ForeignKeyConstraint(['user'], [u'user.id'], name=u'user_experiments_user_fkey')
    )
    op.drop_table('user_projects')
    ### end Alembic commands ###
