"""empty message

Revision ID: 2b753f45c568
Revises: None
Create Date: 2016-04-01 15:51:25.017068

"""

# revision identifiers, used by Alembic.
revision = '2b753f45c568'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_project', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_project', 'project', ['project_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_project', type_='foreignkey')
    op.drop_constraint(None, 'user_project', type_='foreignkey')
    ### end Alembic commands ###
