"""empty message

Revision ID: 2cf6dbdc218a
Revises: 1df9dea0f71a
Create Date: 2015-11-17 15:45:07.490030

"""

# revision identifiers, used by Alembic.
revision = '2cf6dbdc218a'
down_revision = '1df9dea0f71a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import String 

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('commands', postgresql.ARRAY(String(length=256)), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'commands')
    ### end Alembic commands ###
