"""empty message

Revision ID: 2da14eaa0e8a
Revises: 4aff036b9f58
Create Date: 2015-11-17 16:00:53.168574

"""

# revision identifiers, used by Alembic.
revision = '2da14eaa0e8a'
down_revision = '4aff036b9f58'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'duration')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('duration', postgresql.TSRANGE(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
