"""empty message

Revision ID: 3294f9843d1
Revises: 2cf6dbdc218a
Create Date: 2015-11-17 15:46:29.015910

"""

# revision identifiers, used by Alembic.
revision = '3294f9843d1'
down_revision = '2cf6dbdc218a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Integer 

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('responses', postgresql.ARRAY(Integer()), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'responses')
    ### end Alembic commands ###
