"""empty message

Revision ID: 404f8725e18
Revises: 4f588c37d3a7
Create Date: 2015-11-15 12:21:42.907953

"""

# revision identifiers, used by Alembic.
revision = '404f8725e18'
down_revision = '4f588c37d3a7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('experiment')
    # op.drop_constraint(u'dataset_experiment_id_fkey', 'dataset', type_='foreignkey')
    op.drop_column('dataset', 'experiment_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'dataset_experiment_id_fkey', 'dataset', 'experiment', ['experiment_id'], ['id'])
    op.create_table('experiment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('paired', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('chain_types_sequenced', postgresql.ARRAY(VARCHAR(length=20)), autoincrement=False, nullable=True),
    sa.Column('owners_of_experiment', postgresql.ARRAY(VARCHAR(length=20)), autoincrement=False, nullable=True),
    sa.Column('read_access', postgresql.ARRAY(VARCHAR(length=50)), autoincrement=False, nullable=True),
    sa.Column('cell_types_sequenced', postgresql.ARRAY(VARCHAR(length=50)), autoincrement=False, nullable=True),
    sa.Column('isotypes_sequenced', postgresql.ARRAY(VARCHAR(length=10)), autoincrement=False, nullable=True),
    sa.Column('reverse_primer_used_in_rt_step', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('sample_preparation_date', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('sequencing_platform', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('experiment_creation_date', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('species', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('seq_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('template_type', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('experiment_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('work_order', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('lab', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('curated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('analyses_count', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('cell_markers_used', postgresql.ARRAY(VARCHAR(length=100)), autoincrement=False, nullable=True),
    sa.Column('cell_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cell_selection_kit_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('contains_rna_seq_data', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('filenames', postgresql.ARRAY(VARCHAR(length=128)), autoincrement=False, nullable=True),
    sa.Column('gsaf_barcode', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('gsaf_sample_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('lab_notebook_source', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('list_of_polymerases_used', postgresql.ARRAY(VARCHAR(length=100)), autoincrement=False, nullable=True),
    sa.Column('mid_tag', postgresql.ARRAY(VARCHAR(length=100)), autoincrement=False, nullable=True),
    sa.Column('pairing_technique', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('person_who_prepared_library', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('primer_set_name', postgresql.ARRAY(VARCHAR(length=100)), autoincrement=False, nullable=True),
    sa.Column('publications', postgresql.ARRAY(VARCHAR(length=100)), autoincrement=False, nullable=True),
    sa.Column('target_reads', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'experiment_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'experiment_pkey')
    )
    ### end Alembic commands ###
