"""empty message

Revision ID: 44a0454d3b98
Revises: 430bd5ee05dc
Create Date: 2015-11-14 12:49:06.498922

"""

# revision identifiers, used by Alembic.
revision = '44a0454d3b98'
down_revision = '430bd5ee05dc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import String

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('paired', sa.Boolean(), nullable=True),
    sa.Column('chain_types_sequenced', postgresql.ARRAY(String(length=20)), nullable=True),
    sa.Column('owners_of_experiment', postgresql.ARRAY(String(length=20)), nullable=True),
    sa.Column('read_access', postgresql.ARRAY(String(length=50)), nullable=True),
    sa.Column('cell_types_sequenced', postgresql.ARRAY(String(length=50)), nullable=True),
    sa.Column('isotypes_sequenced', postgresql.ARRAY(String(length=10)), nullable=True),
    sa.Column('reverse_primer_used_in_rt_step', sa.String(length=128), nullable=True),
    sa.Column('sample_preparation_date', sa.String(length=128), nullable=True),
    sa.Column('uploaded_by', sa.String(length=128), nullable=True),
    sa.Column('sequencing_platform', sa.String(length=128), nullable=True),
    sa.Column('experiment_creation_date', sa.String(length=128), nullable=True),
    sa.Column('species', sa.String(length=128), nullable=True),
    sa.Column('seq_count', sa.Integer(), nullable=True),
    sa.Column('template_type', sa.String(length=128), nullable=True),
    sa.Column('experiment_name', sa.String(length=128), nullable=True),
    sa.Column('work_order', sa.String(length=128), nullable=True),
    sa.Column('lab', sa.String(length=128), nullable=True),
    sa.Column('curated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiment')
    ### end Alembic commands ###
