"""empty message

Revision ID: 45d9ecbd0b56
Revises: None
Create Date: 2016-03-31 13:33:51.125919

"""

# revision identifiers, used by Alembic.
revision = '45d9ecbd0b56'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('_id', postgresql.JSON(), nullable=True),
    sa.Column('cell_types_sequenced', sa.String(length=256), nullable=True),
    sa.Column('publications', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('species', sa.String(length=128), nullable=True),
    sa.Column('lab', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_experiments',
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('experiment', sa.Integer(), nullable=True),
    sa.Column('read_only', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['experiment'], ['experiment.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    op.add_column(u'dataset', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dataset', 'project', ['project_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    op.drop_column(u'dataset', 'project_id')
    op.drop_table('user_experiments')
    op.drop_table('project')
    ### end Alembic commands ###
