"""empty message

Revision ID: 4a70b8111863
Revises: 92157841e02
Create Date: 2015-11-15 21:18:48.668553

"""

# revision identifiers, used by Alembic.
revision = '4a70b8111863'
down_revision = '92157841e02'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('_id', postgresql.JSON(), nullable=True))
    op.add_column('experiment', sa.Column('analyses_count', postgresql.JSON(), nullable=True))
    op.add_column('experiment', sa.Column('analyses_settings', postgresql.JSON(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment', 'analyses_settings')
    op.drop_column('experiment', 'analyses_count')
    op.drop_column('experiment', '_id')
    ### end Alembic commands ###
