"""empty message

Revision ID: 4aff036b9f58
Revises: b51bb6978ed
Create Date: 2015-11-17 15:48:42.451103

"""

# revision identifiers, used by Alembic.
revision = '4aff036b9f58'
down_revision = 'b51bb6978ed'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import String 

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('commands', postgresql.ARRAY(String(length=1024)), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'commands')
    ### end Alembic commands ###
