"""empty message

Revision ID: 4d1b2f50ef3b
Revises: 2a30473eb01b
Create Date: 2015-11-15 19:40:10.515964

"""

# revision identifiers, used by Alembic.
revision = '4d1b2f50ef3b'
down_revision = '2a30473eb01b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'username')
    ### end Alembic commands ###
