"""empty message

Revision ID: 4d86bb1e6c5
Revises: None
Create Date: 2016-05-26 11:26:17.000522

"""

# revision identifiers, used by Alembic.
revision = '4d86bb1e6c5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('async_task_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('result', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('failed', sa.Boolean(), nullable=True),
    sa.Column('user_alerted', sa.Boolean(), nullable=True),
    sa.Column('user_dismissed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celery_task')
    ### end Alembic commands ###
