"""empty message

Revision ID: 4f588c37d3a7
Revises: 8def69a0aeb
Create Date: 2015-11-15 12:12:09.549958

"""

# revision identifiers, used by Alembic.
revision = '4f588c37d3a7'
down_revision = '8def69a0aeb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment', 'analyses_settings')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('analyses_settings', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    ### end Alembic commands ###
