"""empty message

Revision ID: 5264f2ac86c6
Revises: 2124bb2bb1a7
Create Date: 2016-05-27 08:49:18.740257

"""

# revision identifiers, used by Alembic.
revision = '5264f2ac86c6'
down_revision = '2124bb2bb1a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('log_file_id', sa.Integer(), nullable=True))
    op.add_column('analysis', sa.Column('traceback_file_id', sa.Integer(), nullable=True))
    op.add_column('analysis', sa.Column('zip_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key('log_file_id', 'analysis', 'file', ['log_file_id'], ['id'], use_alter=True)
    op.create_foreign_key('zip_file_id', 'analysis', 'file', ['zip_file_id'], ['id'], use_alter=True)
    op.create_foreign_key('traceback_file_id', 'analysis', 'file', ['traceback_file_id'], ['id'], use_alter=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('traceback_file_id', 'analysis', type_='foreignkey')
    op.drop_constraint('zip_file_id', 'analysis', type_='foreignkey')
    op.drop_constraint('log_file_id', 'analysis', type_='foreignkey')
    op.drop_column('analysis', 'zip_file_id')
    op.drop_column('analysis', 'traceback_file_id')
    op.drop_column('analysis', 'log_file_id')
    ### end Alembic commands ###
