"""empty message

Revision ID: 5284a7a4c5a4
Revises: 5264f2ac86c6
Create Date: 2016-05-27 13:05:07.621828

"""

# revision identifiers, used by Alembic.
revision = '5284a7a4c5a4'
down_revision = '5264f2ac86c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('settings_file_id', sa.Integer(), nullable=True))
    op.create_foreign_key('log_file_id', 'analysis', 'file', ['log_file_id'], ['id'], use_alter=True)
    op.create_foreign_key('zip_file_id', 'analysis', 'file', ['zip_file_id'], ['id'], use_alter=True)
    op.create_foreign_key('traceback_file_id', 'analysis', 'file', ['traceback_file_id'], ['id'], use_alter=True)
    op.create_foreign_key('traceback_file_id', 'analysis', 'file', ['settings_file_id'], ['id'], use_alter=True)
    op.drop_column('file', 's3_available')
    op.drop_column('file', 's3_path')
    op.drop_column('file', 's3_status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('s3_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('file', sa.Column('s3_path', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.add_column('file', sa.Column('s3_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint('traceback_file_id', 'analysis', type_='foreignkey')
    op.drop_constraint('traceback_file_id', 'analysis', type_='foreignkey')
    op.drop_constraint('zip_file_id', 'analysis', type_='foreignkey')
    op.drop_constraint('log_file_id', 'analysis', type_='foreignkey')
    op.drop_column('analysis', 'settings_file_id')
    ### end Alembic commands ###
