"""empty message

Revision ID: 533232921388
Revises: 54e4eb34e735
Create Date: 2015-11-18 23:15:04.724009

"""

# revision identifiers, used by Alembic.
revision = '533232921388'
down_revision = '54e4eb34e735'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('in_use', sa.Boolean(), nullable=True))
    op.add_column('file', sa.Column('s3_path', sa.String(length=256), nullable=True))
    op.add_column('file', sa.Column('transfer_status', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'transfer_status')
    op.drop_column('file', 's3_path')
    op.drop_column('file', 'in_use')
    ### end Alembic commands ###
