"""empty message

Revision ID: 563909923e5d
Revises: 129783c2593b
Create Date: 2015-11-17 19:16:35.261426

"""

# revision identifiers, used by Alembic.
revision = '563909923e5d'
down_revision = '129783c2593b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('analysis_id', sa.Integer(), nullable=True))
    op.add_column('file', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'file_analysis_fkey', 'file', type_='foreignkey')
    op.drop_constraint(u'file_parent_fkey', 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'file', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'file', 'analysis', ['analysis_id'], ['id'])
    op.drop_column('file', 'analysis')
    op.drop_column('file', 'parent')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('parent', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('file', sa.Column('analysis', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key(u'file_parent_fkey', 'file', 'file', ['parent'], ['id'])
    op.create_foreign_key(u'file_analysis_fkey', 'file', 'analysis', ['analysis'], ['id'])
    op.drop_column('file', 'parent_id')
    op.drop_column('file', 'analysis_id')
    ### end Alembic commands ###
