"""empty message

Revision ID: 57f2b4f55ad9
Revises: 2186c8328cc1
Create Date: 2016-04-13 15:07:11.419506

"""

# revision identifiers, used by Alembic.
revision = '57f2b4f55ad9'
down_revision = '2186c8328cc1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('analysis', 'directory')
    #op.drop_column('analysis', 'files_to_analyze')
    #op.drop_column('analysis', 'error')
    #op.drop_column('annotation', 'strand_corrected_sequence')
    op.add_column('dataset', sa.Column('species', sa.String(length=256), nullable=True))
    #op.drop_column('dataset', 'directory')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('dataset', sa.Column('directory', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('dataset', 'species')
    #op.add_column('annotation', sa.Column('strand_corrected_sequence', sa.VARCHAR(), autoincrement=False, nullable=True))
    #op.add_column('analysis', sa.Column('error', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    #op.add_column('analysis', sa.Column('files_to_analyze', postgresql.ARRAY(INTEGER()), autoincrement=False, nullable=True))
    #op.add_column('analysis', sa.Column('directory', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    ### end Alembic commands ###
