"""empty message

Revision ID: 581c5a8a69df
Revises: 2b753f45c568
Create Date: 2016-04-04 13:11:05.173509

"""

# revision identifiers, used by Alembic.
revision = '581c5a8a69df'
down_revision = '2b753f45c568'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('creation_date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'creation_date')
    ### end Alembic commands ###
