"""empty message

Revision ID: 59a53d2f271e
Revises: 182d27742547
Create Date: 2016-04-27 17:36:17.942291

"""

# revision identifiers, used by Alembic.
revision = '59a53d2f271e'
down_revision = '182d27742547'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('celery_task', sa.Column('name', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('celery_task', 'name')
    ### end Alembic commands ###
