"""empty message

Revision ID: 897e5936903
Revises: 394500ecbeb2
Create Date: 2015-11-17 14:18:27.412484

"""

# revision identifiers, used by Alembic.
revision = '897e5936903'
down_revision = '394500ecbeb2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import String

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('cell_types_sequenced', postgresql.ARRAY(String(length=50)), nullable=True))
    op.add_column('dataset', sa.Column('chain_types_sequenced', postgresql.ARRAY(String(length=20)), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'chain_types_sequenced')
    op.drop_column('dataset', 'cell_types_sequenced')
    ### end Alembic commands ###
