"""empty message

Revision ID: 8def69a0aeb
Revises: 44a0454d3b98
Create Date: 2015-11-15 12:03:45.342406

"""

# revision identifiers, used by Alembic.
revision = '8def69a0aeb'
down_revision = '44a0454d3b98'

from alembic import op
import sqlalchemy as sa
from sqlalchemy import String 
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('experiment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dataset', 'experiment', ['experiment_id'], ['id'])
    op.add_column('experiment', sa.Column('analyses_count', sa.String(length=128), nullable=True))
    op.add_column('experiment', sa.Column('analyses_settings', sa.String(length=256), nullable=True))
    op.add_column('experiment', sa.Column('cell_markers_used', postgresql.ARRAY(String(length=100)), nullable=True))
    op.add_column('experiment', sa.Column('cell_number', sa.Integer(), nullable=True))
    op.add_column('experiment', sa.Column('cell_selection_kit_name', sa.String(length=128), nullable=True))
    op.add_column('experiment', sa.Column('contains_rna_seq_data', sa.Boolean(), nullable=True))
    op.add_column('experiment', sa.Column('filenames', postgresql.ARRAY(String(length=128)), nullable=True))
    op.add_column('experiment', sa.Column('gsaf_barcode', sa.String(length=20), nullable=True))
    op.add_column('experiment', sa.Column('gsaf_sample_name', sa.String(length=128), nullable=True))
    op.add_column('experiment', sa.Column('lab_notebook_source', sa.String(length=128), nullable=True))
    op.add_column('experiment', sa.Column('list_of_polymerases_used', postgresql.ARRAY(String(length=100)), nullable=True))
    op.add_column('experiment', sa.Column('mid_tag', postgresql.ARRAY(String(length=100)), nullable=True))
    op.add_column('experiment', sa.Column('pairing_technique', sa.String(length=128), nullable=True))
    op.add_column('experiment', sa.Column('person_who_prepared_library', sa.String(length=128), nullable=True))
    op.add_column('experiment', sa.Column('primer_set_name', postgresql.ARRAY(String(length=100)), nullable=True))
    op.add_column('experiment', sa.Column('publications', postgresql.ARRAY(String(length=100)), nullable=True))
    op.add_column('experiment', sa.Column('target_reads', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiment', 'target_reads')
    op.drop_column('experiment', 'publications')
    op.drop_column('experiment', 'primer_set_name')
    op.drop_column('experiment', 'person_who_prepared_library')
    op.drop_column('experiment', 'pairing_technique')
    op.drop_column('experiment', 'mid_tag')
    op.drop_column('experiment', 'list_of_polymerases_used')
    op.drop_column('experiment', 'lab_notebook_source')
    op.drop_column('experiment', 'gsaf_sample_name')
    op.drop_column('experiment', 'gsaf_barcode')
    op.drop_column('experiment', 'filenames')
    op.drop_column('experiment', 'contains_rna_seq_data')
    op.drop_column('experiment', 'cell_selection_kit_name')
    op.drop_column('experiment', 'cell_number')
    op.drop_column('experiment', 'cell_markers_used')
    op.drop_column('experiment', 'analyses_settings')
    op.drop_column('experiment', 'analyses_count')
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    op.drop_column('dataset', 'experiment_id')
    ### end Alembic commands ###
