"""empty message

Revision ID: b51bb6978ed
Revises: 3294f9843d1
Create Date: 2015-11-17 15:48:33.442743

"""

# revision identifiers, used by Alembic.
revision = 'b51bb6978ed'
down_revision = '3294f9843d1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis', 'commands')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis', sa.Column('commands', postgresql.ARRAY(VARCHAR(length=256)), autoincrement=False, nullable=True))
    ### end Alembic commands ###
