"""empty message

Revision ID: cfd9df6264f
Revises: 26a39132f209
Create Date: 2015-11-19 13:54:38.662648

"""

# revision identifiers, used by Alembic.
revision = 'cfd9df6264f'
down_revision = '26a39132f209'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('primary_data_files_ids', postgresql.ARRAY(sa.Integer()), nullable=True))
    op.drop_column('dataset', 'primary_data_file_ids')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('primary_data_file_ids', postgresql.ARRAY(INTEGER()), autoincrement=False, nullable=True))
    op.drop_column('dataset', 'primary_data_files_ids')
    ### end Alembic commands ###
